// Manuscript text for "Placental Pathology and Infantile Haemangioma in the
// Collaborative Perinatal Project". British English, no first person.
// Citations are written as [@key] and numbered in order of first use by
// build_manuscript.js. Every number in the text comes from outputs/*.csv.

module.exports.title = "Placental Pathology and Infantile Haemangioma in the Collaborative Perinatal Project";
module.exports.runningHead = "Placental Pathology and Infantile Haemangioma";

module.exports.authors = [
  ["Jessica J. Wong, MS", "1"], ["Sunni L. Mumford, PhD", "1,2"], ["Alexa A. Freedman, PhD", "3"],
  ["Linda M. Ernst, MD, MHS", "4,5"], ["Yajnaseni Chakraborti, PhD", "1"], ["David J. Margolis, MD, PhD", "1,6"],
  ["Ellen C. Caniglia, ScD", "1,2"], ["Enrique F. Schisterman, PhD", "1,2"], ["Stefanie N. Hinkle, PhD", "1,2*"],
  ["Ellen C. Francis, PhD", "7*"],
];

module.exports.affiliations = [
  ["1", "Department of Biostatistics, Epidemiology, and Informatics, Perelman School of Medicine, University of Pennsylvania, Philadelphia, PA, USA"],
  ["2", "Department of Obstetrics and Gynecology, Perelman School of Medicine, University of Pennsylvania, Philadelphia, PA, USA"],
  ["3", "Department of Preventive Medicine, Northwestern University Feinberg School of Medicine, Chicago, IL, USA"],
  ["4", "Endeavor Health, Evanston, IL, USA"],
  ["5", "Department of Pathology and Laboratory Medicine, Endeavor Health and Department of Pathology, University of Chicago Pritzker School of Medicine, Chicago, IL, USA"],
  ["6", "Department of Dermatology, Perelman School of Medicine, University of Pennsylvania, Philadelphia, PA, USA"],
  ["7", "Department of Biostatistics and Epidemiology, Rutgers School of Public Health, Rutgers University, Piscataway, NJ, USA"],
  ["*", "Co-senior authors"],
];

module.exports.correspondence = "Stefanie N. Hinkle, PhD, Department of Biostatistics, Epidemiology, and Informatics, Perelman School of Medicine, University of Pennsylvania, 3600 Civic Center Blvd, 5W-101B, Philadelphia, PA 19104, USA. Email: stefanie.hinkle@pennmedicine.upenn.edu";

module.exports.orcid = [
  "Jessica J. Wong: 0009-0002-7642-1613", "Sunni L. Mumford: 0000-0003-0133-3176",
  "Alexa A. Freedman: 0000-0001-9745-7768", "Linda M. Ernst: 0000-0003-0104-5107",
  "Yajnaseni Chakraborti: 0000-0002-6747-8821", "David J. Margolis: 0000-0002-8540-7786",
  "Ellen C. Caniglia: 0000-0002-9891-057X", "Enrique F. Schisterman: 0000-0001-5238-519X",
  "Stefanie N. Hinkle: 0000-0003-4312-708X", "Ellen C. Francis: 0000-0001-8618-045X",
];

module.exports.abstract = [
  ["Introduction", "Infantile haemangioma (IH), the most common tumour of infancy, is a raised, bright-red dermatological lesion appearing within weeks of birth, most often on the head, neck, or trunk, and affects 1.5% to 4.4% of newborns. Perinatal risk factors implicate the maternal-placental-foetal unit, yet placental injury patterns remain unexamined."],
  ["Methods", "This analysis included 45,268 singleton pregnancies from the Collaborative Perinatal Project, a prospective cohort enrolled across 12 US centres (1959 to 1965) with systematic placental histopathology. Exposures were (1) maternal vascular malperfusion (MVM) and (2) acute inflammation (AI), each as present or absent and as a continuous score, and (3) a joint exposure (neither, MVM only, AI only, or both). Standardised paediatrician examinations ascertained IH by age one. Adjusted relative risks (aRR) and 95% confidence intervals (CI) were estimated by modified Poisson regression with 11 covariates, study site, and stabilised inverse probability of censoring weights."],
  ["Results", "MVM was present in 13,119 (29.0%) pregnancies and AI in 10,188 (22.5%). IH developed in 700 of 40,700 infants (1.7%). Neither MVM (aRR 1.14, 95% CI 0.96, 1.35) nor AI (aRR 1.14, 95% CI 0.96, 1.35) was associated with IH, nor were the MVM score (aRR 1.05, 95% CI 0.97, 1.15) or AI score (aRR 1.03, 95% CI 0.98, 1.08). Infants whose placentas showed both MVM and AI had higher IH risk than those with neither (aRR 1.37, 95% CI 1.05, 1.78)."],
  ["Discussion", "Neither placental MVM nor AI was associated with IH, although having both lesions was associated with higher risk."],
];

module.exports.highlights = [
  "Placental pathology and infantile haemangioma were studied in 45,268 pregnancies",
  "Placental MVM and AI alone were not associated with infantile haemangioma",
  "Haemangioma risk was higher when placentas showed both MVM and AI",
  "Placental diagnoses varied several-fold across the 12 study centres",
  "Multicentre placental studies should account for centre and pathologist",
];

module.exports.keywords = "Infantile haemangioma, Placental pathology, Maternal vascular malperfusion, Placental inflammation, Collaborative Perinatal Project, Cohort studies";

// Body: array of [type, text]. Types: h1, h2, p.
module.exports.body = [
  ["h1", "1. Introduction"],
  ["p", "Infantile haemangioma (IH) is the most common tumour of infancy, affecting approximately 1.5% to 4.4% of infants [@sun2024]. IH typically presents as a raised, bright-red lesion in the first weeks after birth, most often on the head, neck, or trunk, and proliferates rapidly during the first months of life before slowly involuting [@holm2024, @chang2008]. Lesions on the face, airway, or other anatomically sensitive sites can cause visual obstruction, airway compromise, ulceration, and lasting disfigurement [@holm2024, @leaute2017]. Despite this burden, the aetiology of IH remains incompletely understood. The most consistently reported risk factors, including female sex, preterm birth, low birthweight, and multiple gestation, together with more variably reported factors such as placenta praevia and pre-eclampsia, point to the maternal-placental-foetal unit as a plausible origin [@ding2020, @haggstrom2007, @munden2014, @schoch2018]."],
  ["p", "Several lines of evidence link IH to the placenta. IH endothelial cells share a distinctive immunophenotype with placental microvessels, including expression of glucose transporter 1, merosin, Lewis Y antigen, and FcγRII [@north2001], and IH and placenta show closely related transcriptional profiles [@barnes2005]. Proliferating IH displays a hypoxia-responsive phenotype, hypoxia-induced mediators of progenitor cell mobilisation are elevated in affected children [@kleinman2007, @harbi2016], and clinical and histological observations have linked placental hypoxia to neonatal haemangioma [@colonna2010]. These observations have led to the hypothesis that placental injury, and the intrauterine hypoxia or inflammation that accompanies it, may prime the development of IH [@drolet2010, @holm2024]. Contemporary placental pathology classifies lesions into injury patterns that reflect distinct biological processes [@khong2016, @redline2021]. Two patterns are of particular relevance. Maternal vascular malperfusion (MVM) reflects impaired uteroplacental perfusion and oxygenation, and acute inflammation (AI) reflects neutrophilic infiltration of the placental membranes and foetal vessels in response to an inflammatory intrauterine milieu [@redline2021, @goldstein2020]."],
  ["p", "Few epidemiological studies have examined the placenta in relation to IH. In a prospective cohort of 594 infants with 27 IH cases, placental anomalies, a composite of clinical and pathological conditions including pre-eclampsia, placenta praevia, and growth restriction, were approximately twice as common in IH-affected pregnancies [@munden2014]. Among 26 very-low-birthweight infants, extensive infarction or retroplacental haematoma was reported in all 13 placentas from infants with IH [@lopez2007], whereas a Swedish case-control study found no association between placental chorangioma and parent-reported IH [@sirotkina2017]. These studies were small, drawn from selected clinical populations, and unadjusted for confounding, and none examined contemporary patterns of placental injury. Placental histopathology is also challenging to study across centres, because diagnostic thresholds for MVM and AI vary between pathologists and institutions [@redline2003, @rocha2026, @freedman2021]."],
  ["p", "The objective of this study was to examine associations of placental MVM and AI, individually and in combination, with paediatrician-ascertained IH by one year of age in the Collaborative Perinatal Project (CPP), a large prospective cohort with systematic placental histopathology and standardised infant examinations across 12 US clinical centres."],

  ["h1", "2. Methods"],
  ["h2", "2.1. Study population"],
  ["p", "The CPP was a prospective cohort study conducted by the National Institute of Neurological Diseases and Stroke to examine perinatal factors in relation to neurological and developmental outcomes in offspring [@hardy2003, @klebanoff2009]. Pregnant women were enrolled at their first antenatal visit at 12 US clinical centres from 1959 to 1965, with deliveries continuing into 1966. Placentas were examined by trained study pathologists at each centre using a standardised protocol [@freedman2025], and offspring underwent standardised examinations by study paediatricians at 12 months of age. The de-identified CPP data are publicly available through the US National Archives and Records Administration."],
  ["p", "Of 59,391 pregnancies (infants) in the CPP, 47,090 had a placental pathology record (Fig. 1). Multiple gestations (n = 933) were excluded because twins may share a placenta, particularly in monochorionic pregnancies, so placental lesions cannot be assigned to the intrauterine exposure of an individual infant, and because multiple gestation is strongly associated with both placental pathology and IH [@ding2020]. Plurality was taken from the CPP delivery record and cross-checked against the placental pathology file. After further excluding pregnancies with a missing MVM score (n = 887) or missing AI data (n = 2), the analytic sample comprised 45,268 singleton pregnancies. This secondary analysis of de-identified, publicly available data was determined exempt by the University of Pennsylvania Institutional Review Board."],

  ["h2", "2.2. Placental pathology"],
  ["p", "Placental examinations recorded individual lesions by anatomical location, including the umbilical cord, membranes, decidua, villi, and intervillous space. Consistent with contemporary classifications [@khong2016, @redline2021], individual lesions were organised by the authors into patterns of injury, as previously described for this cohort [@freedman2025]. The MVM score summed the available MVM lesions (retroplacental haematoma, increased perivillous fibrin deposition, increased syncytial knots, single infarct, multiple infarcts, intervillous thrombus with adjacent villous infarction, decidual vascular thrombosis, fibrinoid necrosis, and atherosis), with one point for each lesion, and two additional points if the placenta had at least one MVM lesion and weighed less than the 10th percentile for gestational age based on an internal CPP reference [@freedman2025]. Four lesions in the current MVM definition were not recorded in the CPP [@freedman2025]. MVM was analysed as present (score of one or more) versus absent, as a continuous score (observed range 0 to 8), and as grade (none, low [score 1 to 2], or high [score 3 or more])."],
  ["p", "AI was defined as neutrophilic infiltration, graded 0 to 3, in any of seven compartments. The amnion and chorion of the membrane roll and of the placental surface represented the maternal inflammatory response, and the umbilical vein, umbilical artery, and foetal surface vessels represented the foetal inflammatory response [@redline2003, @khong2016]. AI was analysed as present versus absent, as a score counting the number of involved compartments (0 to 7), as stage (none, low, or high) as recorded in the CPP placental dataset, and by location (maternal only, foetal only, or both)."],

  ["h2", "2.3. Outcome"],
  ["p", "Study paediatricians examined surviving offspring at approximately 12 months of age using a standardised protocol and recorded IH as definite, suspect, or absent. The primary outcome was definite IH. In a prespecified sensitivity analysis, suspect cases were also classified as IH."],

  ["h2", "2.4. Covariates"],
  ["p", "Confounders were selected a priori as potential common causes of placental pathology and IH and were measured before pregnancy or at enrolment. They were maternal age (continuous), pre-pregnancy body mass index (continuous), race and ethnicity (White [reference], Black, Puerto Rican, or other), education (less than high school [reference], some high school, high school graduate, or some college or more), annual family income (seven categories, with $4,000 to $5,999 as reference), marital status (married or common law [reference], single, or widowed, divorced, or separated), smoking (none [reference], 1 to 19, or 20 or more cigarettes per day), parity (0 [reference], 1, 2, 3, or 4 or more), pre-pregnancy diabetes, chronic hypertension (including superimposed pre-eclampsia), and infant sex (female [reference] or male). Race and ethnicity was included as a marker of social and structural factors that may influence both health and diagnosis. Study site was included in the primary model because placental diagnoses and IH prevalence varied markedly across centres. Gestational age, birthweight, and hypertensive disorders arising during pregnancy were not adjusted for because they may lie on the pathway between placental pathology and IH [@schisterman2009]. Small for gestational age (SGA), shown descriptively, was defined as birthweight below the 10th percentile for gestational age and sex based on an internal CPP reference."],

  ["h2", "2.5. Statistical analysis"],
  ["p", "Missing covariate data (body mass index 8.7%, income 6.3%, education 1.4%, parity 1.0%, smoking 0.8%, and less than 0.1% for other covariates) were imputed by multiple imputation by chained equations (20 datasets, 10 iterations), using all covariates, exposures, and study site as predictors [@vanbuuren2011]. Exposures and outcomes were not imputed. Estimates were combined across datasets using Rubin's rules [@rubin1987]."],
  ["p", "Of the 45,268 infants, 1,834 (4.1%) died before the one-year examination and 2,734 (6.0%) survived without an IH examination. To reduce selection bias from restricting analyses to infants with an observed outcome [@hernan2004], stabilised inverse probability of censoring weights were estimated within each imputed dataset. The denominator model included MVM, AI, all covariates, and study site, and the numerator model included an intercept only [@colehernan2008]. Weights ranged from 0.91 to 1.81."],
  ["p", "Relative risks (RR) and 95% confidence intervals (CI) were estimated with modified Poisson regression [@zou2004] using generalised estimating equations with an exchangeable correlation structure, to account for siblings born to the same mother [@desai2008]. The exposures, (1) MVM and (2) AI, were each examined in separate models, both as binary variables (present versus absent) and as continuous scores (MVM per point and AI per involved compartment). MVM and AI were also examined jointly using (1) a four-category joint exposure that compared placentas with MVM only, AI only, or both against placentas with neither, and (2) a mutually adjusted model that included any MVM and any AI in the same model, to estimate the association of each lesion pattern while holding the other constant. Three models were fitted for each exposure: (1) crude, (2) primary (11 covariates, study site, and weights), and (3) secondary (11 covariates and weights, without study site). For the joint exposure, additive interaction was quantified with the relative excess risk due to interaction (RERI), the attributable proportion, and the synergy index, and multiplicative interaction with the ratio of RRs, with CIs estimated by the delta method from the pooled variance-covariance matrix [@knol2012, @hosmer1992]."],
  ["p", "Sensitivity analyses examined (1) MVM grade and AI stage (i.e., none [reference], low, or high, to assess whether IH risk increased with lesion severity), (2) AI by maternal or foetal involvement (i.e., maternal response only [amnion or chorion], foetal response only [umbilical vessels or foetal surface vessels], or both, compared with no AI), (3) sequential addition of covariate groups and study site, (4) study site as a random intercept instead of a fixed effect, (5) stratification by the Boston centre, where 92.6% of placentas were examined by one pathologist [@freedman2021], versus the other 11 centres, and (6) the broader outcome that included suspect IH."],

  ["h1", "3. Results"],
  ["h2", "3.1. Participants"],
  ["p", "Of 45,268 pregnancies, 29.0% (13,119) had any MVM, 22.5% (10,188) had any AI, and 7.9% (3,554) had both (Table 1). Pregnancies with MVM more often involved women with less than a high school education (19.7% vs 16.3%), pre-pregnancy diabetes (2.1% vs 1.3%), and chronic hypertension (6.3% vs 5.6%). Pregnancies with AI more often involved White women (52.3% vs 47.0%), heavy smoking (20.5% vs 16.6%), and male infants (53.4% vs 50.2%). Of the 40,700 infants (89.9%) examined at one year, 1.7% (700) had definite IH and a further 0.6% (230) had suspect IH (Supplementary Table S1)."],
  ["p", "Across centres, any MVM ranged from 9.8% to 80.3%, any AI from 14.5% to 38.1%, and definite IH from 0.4% to 3.6%, with Boston contributing 41.4% (290/700) of IH cases (Supplementary Table S2)."],

  ["h2", "3.2. MVM, AI, and IH"],
  ["p", "IH occurred in 2.0% (225/11,324) of infants with MVM and 1.6% (475/29,376) of those without, and in 2.0% (181/8,880) of infants with AI and 1.6% (519/31,820) of those without (Table 2). In the primary model, neither MVM (RR 1.14, 95% CI 0.96, 1.35) nor AI (RR 1.14, 95% CI 0.96, 1.35) was associated with IH, and neither was the MVM score (per point, RR 1.05, 95% CI 0.97, 1.15) or the AI score (per involved compartment, RR 1.03, 95% CI 0.98, 1.08). In the mutually adjusted model, estimates were unchanged (MVM RR 1.14, 95% CI 0.96, 1.35, and AI RR 1.13, 95% CI 0.96, 1.34) (Supplementary Table S4). In the secondary model without study site, estimates were larger (MVM RR 1.25, 95% CI 1.07, 1.46, and AI RR 1.20, 95% CI 1.02, 1.42)."],

  ["h2", "3.3. Joint exposure to MVM and AI"],
  ["p", "Compared with placentas that had neither MVM nor AI (IH 1.6%, 364/23,391), IH risk was similar for placentas with MVM only (1.8%, RR 1.08, 95% CI 0.89, 1.32) or AI only (1.9%, RR 1.07, 95% CI 0.86, 1.32), and higher for placentas with both (2.4%, 70/2,895, RR 1.37, 95% CI 1.05, 1.78) (Table 2). The RERI was 0.22 (95% CI \u22120.20, 0.64), the attributable proportion was 0.16 (95% CI \u22120.12, 0.44), and the ratio of RRs was 1.18 (95% CI 0.83, 1.68). These estimates were compatible with, but did not establish, interaction on either scale (Supplementary Table S5)."],

  ["h2", "3.4. Sensitivity analyses"],
  ["p", "IH risk did not increase with lesion severity. Compared with no MVM, the RR was 1.15 (95% CI 0.96, 1.37) for low-grade and 1.09 (95% CI 0.77, 1.55) for high-grade MVM. Compared with no AI, the RR was 1.26 (95% CI 1.02, 1.55) for low-stage and 1.00 (95% CI 0.78, 1.28) for high-stage AI (Supplementary Table S6). By maternal or foetal involvement, RRs were 1.07 (95% CI 0.81, 1.43) for a maternal response only, 1.12 (95% CI 0.86, 1.47) for a foetal response only, and 1.20 (95% CI 0.94, 1.55) for both (Supplementary Table S7)."],
  ["p", "Adjustment for the 11 covariates changed estimates little, and almost all of the difference between crude and primary estimates arose when study site was added (Supplementary Table S3). Results were similar when study site was modelled as a random effect (MVM RR 1.16, 95% CI 0.98, 1.37, and AI RR 1.15, 95% CI 0.97, 1.36) (Supplementary Table S9). In Boston, the RR was 1.11 (95% CI 0.87, 1.42) for MVM and 1.28 (95% CI 1.00, 1.63) for AI, compared with 1.14 (95% CI 0.90, 1.44) and 1.03 (95% CI 0.82, 1.31) at the other 11 centres (Supplementary Table S8). AI was recorded more often in Boston than elsewhere (27.6% vs 20.9%), whereas MVM prevalence was similar (29.8% vs 28.7%). Foetal-only inflammation, which involved the umbilical vein in 87.8% of cases, had the largest crude estimate of any AI category (RR 1.67, 95% CI 1.29, 2.18), which fell to 1.12 after adjustment for study site. Of the 2,224 placentas with foetal-only inflammation among infants examined at one year, 61.1% (1,359) were from Boston, where this pattern was recorded in 14.1% of placentas compared with 0.9% to 8.1% at the other centres."],
  ["p", "When suspect IH was included in the outcome (930 cases), estimates were similar (MVM RR 1.13, 95% CI 0.98, 1.30, and AI RR 1.10, 95% CI 0.95, 1.27) (Supplementary Table S10). Inverse probability weighting changed no estimate by more than 0.01."],

  ["h1", "4. Discussion"],
  ["h2", "4.1. Principal findings"],
  ["p", "In this prospective cohort of 45,268 singleton pregnancies, neither placental MVM nor AI was associated with IH after accounting for study site. Point estimates were slightly above the null, and the confidence intervals could not exclude a small increase in risk, but they make RRs larger than about 1.35 unlikely for either lesion pattern. IH risk did not increase with MVM grade or AI stage. IH risk was higher when both MVM and AI were present, although the interaction estimate was imprecise. The larger estimates observed without adjustment for study site reflected differences between centres rather than associations within centres."],

  ["h2", "4.2. Study site and placental diagnosis"],
  ["p", "Variation in placental diagnosis across centres is central to interpreting these findings, because the associations seen without adjustment for study site arose largely from comparisons between centres. MVM was recorded in 9.8% of placentas at one CPP centre and 80.3% at another, a range too wide to reflect differences in the populations alone. This is consistent with evidence that agreement between pathologists is only slight to fair for MVM, even when Amsterdam criteria are applied [@rocha2026, @redline2022], and that agreement for AI, although high for its presence, is lower for staging [@redline2003, @redline2022]. Because IH prevalence also varied across centres, possibly reflecting differences in populations and in paediatric ascertainment, centre-level differences in diagnostic thresholds can confound the association between a recorded placental lesion and IH. Adjustment for study site compares placentas read within the same centre, and the resulting attenuation (MVM from 1.25 to 1.14, AI from 1.20 to 1.14) is consistent with removal of between-centre confounding. Estimates were similar when site was modelled as a random effect."],
  ["p", "The Boston centre, where one pathologist examined 92.6% of placentas [@freedman2021], recorded AI more often than other centres, including foetal inflammation without a maternal response, a pattern that should be uncommon because a foetal response ordinarily follows a maternal one [@redline2003, @gotsch2007]. This suggests a lower diagnostic threshold, and shows that consistency within a single reader does not ensure comparability with other readers. Multicentre placental studies should therefore account for centre and, where possible, reader."],

  ["h2", "4.3. Comparison with previous studies"],
  ["p", "Earlier studies reported that placental anomalies were more common in pregnancies affected by IH [@munden2014, @lopez2007]. These studies were small, used composite or selected exposures, and did not adjust for confounding, and the present estimates are considerably smaller. The findings are also consistent with a previous CPP analysis that found no clear association between hypertensive disorders of pregnancy and IH [@wong2026]. This may reflect that clinically defined hypertensive disorders are not consistently accompanied by MVM [@freedman2023]. The findings also agree with evidence that the association between pre-eclampsia and IH in administrative data largely reflects greater surveillance of infants with longer neonatal stays [@auger2017]. Together, these studies suggest that placental vascular injury is not a major determinant of IH, and that any contribution is likely to be small."],

  ["h2", "4.4. Biological interpretation"],
  ["p", "The hypoxia hypothesis offers a plausible framework for a link between MVM and IH. IH shares markers and transcriptional programmes with placental tissue [@north2001, @barnes2005], and hypoxia-induced mediators of progenitor cell mobilisation are elevated in children with IH [@kleinman2007, @drolet2010]. However, this evidence demonstrates a shared or hypoxia-responsive phenotype within established lesions rather than a causal effect of placental malperfusion, and genetic studies have not supported a maternal origin of IH cells [@pittman2006]. The null finding for MVM does not refute the hypothesis, because a small effect cannot be excluded, but it provides no support for a strong link. The absence of a gradient by MVM grade argues against a strong effect, although incomplete capture of MVM lesions and misclassification would attenuate a true gradient. One possibility, consistent with the predominantly postnatal growth of IH, is that antenatal placental injury expands a susceptible population of endothelial progenitor cells, whereas postnatal hormonal and angiogenic signals determine whether it proliferates [@holm2024, @chang2008]. This two-stage model has not been tested prospectively."],
  ["p", "AI is a less plausible cause of IH. Histological AI generally reflects an inflammatory process close to delivery, often of infectious origin, and a direct effect on localised skin angiogenesis would require a systemic foetal inflammatory response with lasting consequences [@gotsch2007, @goldstein2020]. The higher estimate for low-stage than high-stage AI, the absence of a clear gradient from maternal to foetal involvement, and the centre-specific pattern of foetal-only inflammation all argue against a causal interpretation. For retinopathy of prematurity, another postnatal disorder of angiogenesis, the association with chorioamnionitis is largely explained by lower gestational age [@villamor2018], and AI may similarly mark pathways to preterm birth rather than act on IH directly."],
  ["p", "The higher risk when MVM and AI co-occurred is compatible with a multiple-hit model in which vascular and inflammatory insults converge on foetal angiogenic signalling [@holm2024, @goldstein2020]. However, the interaction estimate was imprecise and compatible with no departure from additivity, neither lesion showed a dose-response, and the joint category was one of several related contrasts. This finding should therefore be regarded as hypothesis-generating."],

  ["h2", "4.5. Strengths and limitations"],
  ["p", "Strengths of this study include its prospective design, in which placentas were examined at delivery before any infant outcome was known, and the standardised paediatrician examination of all surviving infants regardless of exposure, which avoids the referral and surveillance biases of clinic-based and administrative studies. More than 45,000 placentas were examined under a common protocol. The analysis addressed confounding by centre, missing covariate data, selection due to death and loss to follow-up, and clustering of siblings."],
  ["p", "Several limitations should be considered. First, despite the size of the cohort, IH is uncommon, and the study had limited power to detect small associations. Power to detect the observed RR of 1.14 was approximately 36% for MVM and 32% for AI, so small effects cannot be excluded. Second, the CPP predates the Amsterdam consensus, four lesions in the current MVM definition were not recorded [@freedman2025], and both random and centre-specific exposure misclassification are likely. Third, IH was ascertained at a single examination at 12 months. Most IH reach their maximum size by five months of age and remain visible at one year [@chang2008], but small or involuting lesions may have been missed, and the diagnostic categories of the 1960s predate the modern classification of vascular anomalies. Outcome misclassification unrelated to placental pathology would most likely attenuate associations. Fourth, differences in IH ascertainment across centres may not be fully captured by adjustment for site. Fifth, residual confounding is possible, including by maternal history of angioma, an established risk factor that was not recorded [@fuxench2024]. Finally, gestational age and birthweight were not adjusted for because they may mediate effects of placental pathology [@schisterman2009], so estimates represent total effects."],

  ["h2", "4.6. Future directions"],
  ["p", "Future studies should examine placental pathology with central, blinded review using current Amsterdam definitions, duplicate reading of a calibration subset, and recorded pathologist identity. Linking placental lesions to cord-blood markers of foetal inflammation and hypoxia, and to serial dermatological examinations during the first months of life, would distinguish maternal from foetal effects and capture both the occurrence and growth of IH. Prespecified analyses of MVM and AI interaction, and formal mediation analyses through preterm birth and foetal growth, would clarify whether combined placental injury contributes to IH. Whether IH is associated with perinatal infection, which often underlies acute placental inflammation, also warrants study. Modifiable upstream determinants of placental injury, such as maternal diet, environmental exposures, and hypertensive disorders, are a research priority, although evidence linking these exposures to IH through placental pathology is currently lacking."],

  ["h1", "5. Conclusion"],
  ["p", "In this large prospective cohort, neither placental MVM nor AI was associated with IH after accounting for study site, although IH risk was higher when both were present. Variation in placental diagnosis across centres strongly influenced the estimates, underscoring the importance of accounting for centre and, where possible, pathologist in multicentre placental research. Larger studies with centralised placental review are needed to determine whether combined placental injury contributes to IH."],
];

module.exports.declarations = [
  ["CRediT authorship contribution statement", "Jessica J. Wong: Conceptualization, Methodology, Formal analysis, Data curation, Visualization, Funding acquisition, Writing – original draft. Sunni L. Mumford: Methodology, Writing – review & editing. Alexa A. Freedman: Data curation, Methodology, Writing – review & editing. Linda M. Ernst: Methodology, Writing – review & editing. Yajnaseni Chakraborti: Data curation, Methodology, Writing – review & editing. David J. Margolis: Conceptualization, Writing – review & editing. Ellen C. Caniglia: Methodology, Writing – review & editing. Enrique F. Schisterman: Methodology, Writing – review & editing. Stefanie N. Hinkle: Conceptualization, Methodology, Supervision, Writing – review & editing. Ellen C. Francis: Conceptualization, Methodology, Supervision, Writing – review & editing."],
  ["Declaration of competing interest", "The authors declare that they have no known competing financial interests or personal relationships that could have appeared to influence the work reported in this paper."],
  ["Funding", "This work was supported by (1) the National Institute of Allergy and Infectious Diseases of the National Institutes of Health (F31AI198148, JJW) and (2) a National Research Grant from The Gerber Foundation (10105208, JJW). The funders had no role in the study design, collection, analysis or interpretation of data, writing of the report, or the decision to submit the article for publication."],
  ["Acknowledgements", "The authors thank the women and children who participated in the Collaborative Perinatal Project, the study staff at the 12 clinical centres, and the US National Archives and Records Administration for providing access to the study data (https://www.archives.gov/research/electronic-records/nih.html)."],
  ["Data availability", "The Collaborative Perinatal Project data are publicly available through the US National Archives and Records Administration (Identifier: 606622). Analysis code is available from the corresponding author on request."],
  ["Declaration of generative AI and AI-assisted technologies in the manuscript preparation process", "During the preparation of this work the authors used Claude (Anthropic) to assist with statistical programming, checking of analyses, and drafting and language editing of the manuscript, and ChatGPT Deep Research (OpenAI) to assist with literature searching. After using these tools, the authors reviewed and edited the content as needed and take full responsibility for the content of the published article."],
];

module.exports.figureLegends = [
  ["Fig. 1.", "Flow of participants in the Collaborative Perinatal Project. AI, acute inflammation. IH, infantile haemangioma. MVM, maternal vascular malperfusion."],
];

// Elsevier numbered style. [FLAG] marks entries whose details should be checked.
module.exports.references = {
  sun2024: "Y. Sun, J. Zhao, Y. Meng, et al., The prevalence, complications, and risk factors for infantile hemangioma: a systematic review and meta-analysis, Int. J. Dermatol. 63 (2024) 737-746. https://doi.org/10.1111/ijd.17062",
  holm2024: "A. Holm, J.B. Mulliken, J. Bischoff, Infantile hemangioma: the common and enigmatic vascular tumor, J. Clin. Invest. 134 (2024) e172836. https://doi.org/10.1172/JCI172836",
  chang2008: "L.C. Chang, A.N. Haggstrom, B.A. Drolet, et al., Growth characteristics of infantile hemangiomas: implications for management, Pediatrics 122 (2008) 360-367. https://doi.org/10.1542/peds.2007-2767",
  leaute2017: "C. Léauté-Labrèze, J.I. Harper, P.H. Hoeger, Infantile haemangioma, Lancet 390 (2017) 85-94. https://doi.org/10.1016/S0140-6736(16)00645-0",
  ding2020: "Y. Ding, J.Z. Zhang, S.R. Yu, F. Xiang, X.J. Kang, Risk factors for infantile hemangioma: a meta-analysis, World J. Pediatr. 16 (2020) 377-384. https://doi.org/10.1007/s12519-019-00327-2",
  haggstrom2007: "A.N. Haggstrom, B.A. Drolet, E. Baselga, et al., Prospective study of infantile hemangiomas: demographic, prenatal, and perinatal characteristics, J. Pediatr. 150 (2007) 291-294. https://doi.org/10.1016/j.jpeds.2006.12.003",
  munden2014: "A. Munden, R. Butschek, W.L. Tom, et al., Prospective study of infantile haemangiomas: incidence, clinical characteristics and association with placental anomalies, Br. J. Dermatol. 170 (2014) 907-913. https://doi.org/10.1111/bjd.12804",
  schoch2018: "J. Schoch, M. Hunjan, K. Anderson, et al., Temporal trends in prenatal risk factors for the development of infantile hemangiomas, Pediatr. Dermatol. 35 (2018) 787-791. https://doi.org/10.1111/pde.13659",
  north2001: "P.E. North, M. Waner, A. Mizeracki, et al., A unique microvascular phenotype shared by juvenile hemangiomas and human placenta, Arch. Dermatol. 137 (2001) 559-570. https://doi.org/10.1001/archderm.137.5.559",
  barnes2005: "C.M. Barnés, S. Huang, A. Kaipainen, et al., Evidence by molecular profiling for a placental origin of infantile hemangioma, Proc. Natl. Acad. Sci. U. S. A. 102 (2005) 19097-19102. https://doi.org/10.1073/pnas.0509579102",
  kleinman2007: "M.E. Kleinman, M.R. Greives, S.S. Churgin, et al., Hypoxia-induced mediators of stem/progenitor cell trafficking are increased in children with hemangioma, Arterioscler. Thromb. Vasc. Biol. 27 (2007) 2664-2670. https://doi.org/10.1161/ATVBAHA.107.150284",
  harbi2016: "S. Harbi, R. Wang, M. Gregory, et al., Infantile hemangioma originates from a dysregulated but not fully transformed multipotent stem cell, Sci. Rep. 6 (2016) 35811. https://doi.org/10.1038/srep35811",
  colonna2010: "V. Colonna, L. Resta, A. Napoli, E. Bonifazi, Placental hypoxia and neonatal haemangioma: clinical and histological observations, Br. J. Dermatol. 162 (2010) 208-209. https://doi.org/10.1111/j.1365-2133.2009.09493.x",
  drolet2010: "B.A. Drolet, I.J. Frieden, Characteristics of infantile hemangiomas as clues to pathogenesis: does hypoxia connect the dots?, Arch. Dermatol. 146 (2010) 1295-1299. https://doi.org/10.1001/archdermatol.2010.1295",
  khong2016: "T.Y. Khong, E.E. Mooney, I. Ariel, et al., Sampling and definitions of placental lesions: Amsterdam Placental Workshop Group consensus statement, Arch. Pathol. Lab. Med. 140 (2016) 698-713. https://doi.org/10.5858/arpa.2015-0225-CC",
  redline2021: "R.W. Redline, S. Ravishankar, C.M. Bagby, S.T. Saab, S. Zarei, Four major patterns of placental injury: a stepwise guide for understanding and implementing the 2016 Amsterdam consensus, Mod. Pathol. 34 (2021) 1074-1092. https://doi.org/10.1038/s41379-021-00747-4",
  goldstein2020: "J.A. Goldstein, K. Gallagher, C. Beck, R. Kumar, A.D. Gernand, Maternal-fetal inflammation in the placenta and the developmental origins of health and disease, Front. Immunol. 11 (2020) 531543. https://doi.org/10.3389/fimmu.2020.531543",
  lopez2007: "J.C. López Gutiérrez, L.F. Avila, G. Sosa, M. Patron, Placental anomalies in children with infantile hemangioma, Pediatr. Dermatol. 24 (2007) 353-355. https://doi.org/10.1111/j.1525-1470.2007.00450.x",
  sirotkina2017: "M. Sirotkina, K. Douroudis, C.F. Wahlgren, M. Westgren, N. Papadogiannakis, Exploring the association between chorangioma and infantile haemangioma in singleton and multiple pregnancies: a case-control study in a Swedish tertiary centre, BMJ Open 7 (2017) e015539. https://doi.org/10.1136/bmjopen-2016-015539",
  redline2003: "R.W. Redline, O. Faye-Petersen, D. Heller, et al., Amniotic infection syndrome: nosology and reproducibility of placental reaction patterns, Pediatr. Dev. Pathol. 6 (2003) 435-448. https://doi.org/10.1007/s10024-003-7070-y",
  rocha2026: "M.L. Rocha, T. Menter, S. Zekic Tomas, et al., Reproducibility of the Amsterdam consensus criteria for maternal vascular malperfusion (MVM): a multicenter evaluation of perinatal pathologists, J. Perinat. Med. 54 (2026) 811-815. https://doi.org/10.1515/jpm-2025-0518",
  freedman2021: "A.A. Freedman, et al., Adverse pregnancy outcomes following the assassination of John F. Kennedy in 1963, Matern. Child Health J. (2021). https://doi.org/10.1007/s10995-021-03139-x [FLAG: add co-authors, volume, and pages]",
  hardy2003: "J.B. Hardy, The Collaborative Perinatal Project: lessons and legacy, Ann. Epidemiol. 13 (2003) 303-311. https://doi.org/10.1016/s1047-2797(02)00479-9",
  klebanoff2009: "M.A. Klebanoff, The Collaborative Perinatal Project: a 50-year retrospective, Paediatr. Perinat. Epidemiol. 23 (2009) 2-8. https://doi.org/10.1111/j.1365-3016.2008.00984.x",
  freedman2025: "A.A. Freedman, G.E. Miller, A.D. Franklin, et al., Placental pathology and blood pressure at age 7: a longitudinal discordant twin analysis, Arterioscler. Thromb. Vasc. Biol. 45 (2025) 312-322. https://doi.org/10.1161/ATVBAHA.124.321666",
  schisterman2009: "E.F. Schisterman, S.R. Cole, R.W. Platt, Overadjustment bias and unnecessary adjustment in epidemiologic studies, Epidemiology 20 (2009) 488-495. https://doi.org/10.1097/EDE.0b013e3181a819a1",
  vanbuuren2011: "S. van Buuren, K. Groothuis-Oudshoorn, mice: multivariate imputation by chained equations in R, J. Stat. Softw. 45 (2011) 1-67. https://doi.org/10.18637/jss.v045.i03",
  rubin1987: "D.B. Rubin, Multiple Imputation for Nonresponse in Surveys, John Wiley & Sons, New York, 1987.",
  hernan2004: "M.A. Hernán, S. Hernández-Díaz, J.M. Robins, A structural approach to selection bias, Epidemiology 15 (2004) 615-625. https://doi.org/10.1097/01.ede.0000135174.63482.43",
  colehernan2008: "S.R. Cole, M.A. Hernán, Constructing inverse probability weights for marginal structural models, Am. J. Epidemiol. 168 (2008) 656-664. https://doi.org/10.1093/aje/kwn164",
  zou2004: "G. Zou, A modified Poisson regression approach to prospective studies with binary data, Am. J. Epidemiol. 159 (2004) 702-706. https://doi.org/10.1093/aje/kwh090",
  desai2008: "M. Desai, M.D. Begg, A comparison of regression approaches for analyzing clustered data, Am. J. Public Health 98 (2008) 1425-1429. https://doi.org/10.2105/AJPH.2006.108233",
  knol2012: "M.J. Knol, T.J. VanderWeele, Recommendations for presenting analyses of effect modification and interaction, Int. J. Epidemiol. 41 (2012) 514-520. https://doi.org/10.1093/ije/dyr218",
  hosmer1992: "D.W. Hosmer, S. Lemeshow, Confidence interval estimation of interaction, Epidemiology 3 (1992) 452-456. https://doi.org/10.1097/00001648-199209000-00012",
  wong2026: "J.J. Wong, Y. Chakraborti, E.C. Caniglia, et al., Association between hypertensive disorders of pregnancy and infantile vascular anomalies in the Collaborative Perinatal Project, AJE Adv. 2 (2026) uuag016. https://doi.org/10.1093/ajeadv/uuag016",
  auger2017: "N. Auger, W.D. Fraser, L. Arbour, et al., Pre-eclampsia and risk of infantile haemangioma, Br. J. Dermatol. 176 (2017) 371-377. https://doi.org/10.1111/bjd.14958",
  pittman2006: "K.M. Pittman, H.W. Losken, M.E. Kleinman, et al., No evidence for maternal-fetal microchimerism in infantile hemangioma: a molecular genetic investigation, J. Invest. Dermatol. 126 (2006) 2533-2538. https://doi.org/10.1038/sj.jid.5700516",
  gotsch2007: "F. Gotsch, R. Romero, J.P. Kusanovic, et al., The fetal inflammatory response syndrome, Clin. Obstet. Gynecol. 50 (2007) 652-683. https://doi.org/10.1097/GRF.0b013e31811ebef6",
  villamor2018: "E. Villamor-Martinez, et al., Chorioamnionitis as a risk factor for retinopathy of prematurity: an updated systematic review and meta-analysis, PLoS One 13 (2018) e0205838. https://doi.org/10.1371/journal.pone.0205838 [FLAG: add co-authors]",
  freedman2023: "A.A. Freedman, et al., Patterns of placental pathology associated with preeclampsia, Placenta (2023). PMID: 37336159 [FLAG: add co-authors, volume, pages, and DOI]",
  redline2022: "R.W. Redline, T. Vik, A. Heerema-McKenney, et al., Interobserver reliability for identifying specific patterns of placental injury as defined by the Amsterdam classification, Arch. Pathol. Lab. Med. 146 (2022) 372-378. https://doi.org/10.5858/arpa.2020-0753-OA",
  fuxench2024: "Z.C. Chiesa Fuxench, N. Mitra, J. Wong, O. Hoffstad, S. Hinkle, D.J. Margolis, Maternal history of angioma is associated with infantile hemangioma and port-wine stain in children: a population-based, cohort study of mother-child pairs from the United Kingdom, Arch. Dermatol. Res. 316 (2024) 506. https://doi.org/10.1007/s00403-024-03247-y",
};
