// Response-to-coauthors table: [co-author, comment, response, where]

module.exports.intro = "Thank you all for your thoughtful comments. The analysis was re-run on a corrected sample (45,268 singleton pregnancies, 40,700 with an observed outcome, 700 definite IH cases), study site was moved into the primary model, and the joint MVM and AI exposure was moved into Table 2. The findings are now more modest than in the previous draft, so the Abstract, Results, and Discussion have been rewritten. Each comment is listed below with the change made and where to find it.";

module.exports.rows = [
  ["Ellen Francis", "\"Each independently\" reads like a mutually adjusted model.", "Removed \"independently\" throughout. A mutually adjusted model is now reported, and estimates did not change (MVM 1.14, AI 1.13).", "Results 3.2, Table S4"],
  ["Ellen Francis", "Introduction sentences are dense and long.", "Introduction rewritten with shorter sentences and four focused paragraphs.", "Introduction"],
  ["Ellen Francis", "Be specific about what the placenta offers, and how IH relates to placental injury.", "Paragraph 2 now sets out the shared placental phenotype, hypoxia evidence, and the two injury patterns examined.", "Introduction, paragraph 2"],
  ["Ellen Francis", "What can be done about MVM or AI? Are there intervention targets or upstream dietary or environmental factors?", "Added to Future directions as a research priority, with a caution that evidence linking these exposures to IH through placental pathology is currently lacking.", "Discussion 4.6"],
  ["Ellen Francis", "Does the placenta prime the pathway while postnatal factors shape the phenotype?", "Discussed briefly as a hypothesis within the biological interpretation, without overstating support given the modest estimates.", "Discussion 4.4"],
  ["Ellen Francis", "Make the conclusion forward-looking rather than calling for replication.", "Conclusion and Future directions now propose centralised placental review, cord-blood markers, serial skin examinations, prespecified interaction, and mediation analyses.", "Discussion 4.6, Conclusion"],
  ["Ellen Francis (September)", "Move the joint MVM and AI results into the main results and Table 2.", "Done. Table 2 shows neither (reference), MVM only, AI only, and both. All four groups are shown so the reference and single-lesion estimates are visible.", "Table 2, Results 3.3"],
  ["Ellen Francis and Stefanie Hinkle", "Adjust for study site in the primary model, and show sequential adjustment and Boston versus other sites.", "Site-adjusted model is now primary, with the no-site model as secondary. Sequential adjustment, Boston stratification, site as a random effect, adjustment for pathologist, and the site terms from the primary model are in the supplement.", "Methods 2.4 and 2.5, Tables S2, S3, S8, S10, S11"],
  ["Stefanie Hinkle", "Were Boston placentas read correctly by a single pathologist? Report the stratified results.", "Added a construct validity check comparing expected associations with preterm birth, SGA, pre-eclampsia, and spontaneous labour in Boston and other centres, and the Boston stratified results. Boston recorded more AI and far more foetal-only inflammation.", "Results 3.4 and 3.5, Discussion 4.2, Tables S8 and S9"],
  ["Stefanie Hinkle", "Likely a power issue given the rare outcome, but the signal is still there.", "Framing revised to modest, imprecise associations. A power statement was added (80% power for RR 1.25 for MVM and 1.27 for AI, about 35% power for the observed RR of 1.14), as required by Placenta.", "Abstract, Methods 2.5, Discussion 4.5"],
  ["Alexa Freedman", "Remove \"independent\", which implies one model with both exposures.", "Removed throughout.", "Throughout"],
  ["Alexa Freedman", "Do not call these placental tissue studies, since one is mainly clinical conditions.", "Prior studies are now described by their actual exposures (a composite of clinical and pathological anomalies, histological lesions, or chorangioma).", "Introduction, paragraph 3"],
  ["Alexa Freedman", "Use \"injury-level\" because each category includes multiple lesions.", "Now described as injury patterns throughout.", "Introduction, Methods 2.2"],
  ["Alexa Freedman", "Enrolment ended in 1965, with deliveries through 1966.", "Corrected.", "Abstract, Methods 2.1"],
  ["Alexa Freedman", "Consider including study site because pathology varies by site.", "Study site is now in the primary model, and variation in placental diagnosis across sites is a central theme of the Discussion.", "Methods 2.4, Discussion 4.2, Table S2"],
  ["Alexa Freedman", "Look at AI stage (none, low, high) for a dose-response.", "Done. No dose-response for AI stage (low 1.26, high 1.00) or MVM grade (low 1.15, high 1.09).", "Results 3.4, Table S6"],
  ["Alexa Freedman and Linda Ernst", "What happens if both MVM and AI are in the model?", "Mutually adjusted estimates are unchanged (Table S4). The joint exposure shows higher risk only when both are present (RR 1.37).", "Results 3.2 and 3.3, Tables 2 and S4"],
  ["Alexa Freedman", "Describe prior anomalies as clinically defined and fix the directionality (pathology leads to clinical diagnosis).", "The previous paragraph was removed in the rewrite. Remaining text describes these as composite clinical and pathological conditions without implying that clinical conditions cause the pathology.", "Introduction, Discussion 4.3"],
  ["Alexa Freedman", "Cite her placental pathology in pre-eclampsia paper.", "Cited to explain why the null CPP finding for hypertensive disorders does not conflict with a role for MVM.", "Discussion 4.3"],
  ["Alexa Freedman", "Give the typical age of IH involution to support the one-year examination.", "Added growth characteristics (most IH reach maximum size by five months and remain visible at one year).", "Discussion 4.5"],
  ["Alexa Freedman", "Discordant siblings to control maternal factors.", "Explored. Only 78 mothers were discordant for both IH and MVM (73 for AI), and estimates were too imprecise to be informative.", "Results 3.5, Table S13"],
  ["Alexa Freedman", "Directionality: placental pathology to PTB or LBW to IH, and mediation as a next step.", "Gestational age and birthweight are described as potential mediators, estimates are described as total effects, and mediation is listed as a future direction.", "Methods 2.4, Discussion 4.5 and 4.6"],
  ["Alexa Freedman", "Overall column in Table S1 should be the IH sample, not the whole sample.", "Table S1 now uses the 40,700 infants with an observed outcome throughout.", "Table S1"],
  ["Alexa Freedman", "Parity numbers in Table S1 look off.", "Table S1 was rebuilt from the corrected sample, and parity now sums correctly.", "Table S1"],
  ["Linda Ernst", "The twin exclusion rationale is wrong (attribution is a labelling issue).", "Rationale revised to follow Linda's earlier explanation: twins may share a placenta, particularly monochorionic twins, so lesions cannot be assigned to one infant, and multiple gestation is strongly related to both placental pathology and IH.", "Methods 2.1"],
  ["Linda Ernst", "Maternal versus foetal acute inflammation (MIR and FIR).", "Done. RRs were 1.07 for maternal only, 1.12 for foetal only, and 1.20 for both. Foetal-only inflammation was concentrated in Boston.", "Results 3.4, Table S7"],
  ["Linda Ernst", "Effects of MVM and AI together, and is there synergy?", "Joint exposure in Table 2. Additive and multiplicative interaction were estimated (RERI 0.22, 95% CI −0.20, 0.64), compatible with but not establishing synergy.", "Results 3.3, Table S5"],
  ["Linda Ernst", "AI is acute, often infectious, and a hard mechanism to explain. Reviewers may pick on it.", "The Discussion now states that AI is a less plausible cause, and gives the reasons (timing, no stage gradient, centre-specific foetal-only pattern, analogy with retinopathy of prematurity).", "Discussion 4.4"],
  ["Linda Ernst", "Edits: \"by the authors\" for the grouping of lesions, \"MVM lesion\", \"placental MVM or AI\".", "Accepted.", "Methods 2.2, Introduction"],
  ["Linda Ernst", "British spelling with no British authors.", "British spelling was kept to match the journal's options and is now used consistently (for example enrolment, foetal, paediatrician).", "Throughout"],
];

module.exports.questions = [
  "Alexa: please confirm the exact MVM lesion list and scoring (the text lists nine available lesions), and the rule used to define AI stage (low vs high) in the dataset.",
  "Alexa: please confirm the names of the 12 CPP study sites (only Boston is confirmed from the data).",
  "Linda: does foetal-only inflammation (mostly umbilical vein phlebitis without a maternal response) in 14% of Boston placentas look like a reading convention rather than true biology?",
  "Linda: are there IH-relevant infection variables in the CPP that would help address the question of whether IH sorts with infection?",
  "All: please confirm your CRediT roles, funding to acknowledge, and competing interests.",
];
